version: '3.9'

services:
    
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    container_name: splunk-otel-collector
    restart: always
    env_file:
     - collector.env
    ports:
      - 55681:55681
      - 13133:13133
      - 14250:14250
      - 14268:14268
      - 4317:4317
      - 4318:4318
      - 6060:6060
      - 8888:8888
      - 9080:9080
      - 9411:9411
      - 9943:9943

  server:
    image: server
    container_name: server
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: always
    env_file: 
      - server.env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
    ports: 
      - 3000:3000

  client:
    image: client
    container_name: client
    build:
      context: ../client
      dockerfile: Dockerfile
    restart: always
    env_file: 
      - client.env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://splunk-otel-collector:4317
